CREATE TABLE EMPLEADO(
    DNI_EMP VARCHAR(9),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI_EMP)
);

CREATE TABLE CLIENTE(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    DIRECCION VARCHAR(30),
    TELEFONO VARCHAR(11),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR(5),
    CANTIDAD_PRODUCTO INT(5),
    PRECIO_TOTAL DOUBLE(5,2),
    DNI_CLIENTE VARCHAR(9),
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
);

CREATE TABLE PRODUCTO(
    ID VARCHAR(5),
    MARCA VARCHAR(20),
    PRECIO DOUBLE(5,2),
    STOCK INT(5),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID)
);

CREATE TABLE ALMACEN(
    ID_ALMACEN VARCHAR(5),
    LOCALIZACION VARCHAR(20),
    CONSTRAINT PK_ALMACEN PRIMARY KEY (ID_ALMACEN)
);

