CREATE TABLE EMPLEADO(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR(5),
    CANTIDAD_PRODUCTO NUMBER(5),
    PRECIO_TOTAL NUMBER(5,2)
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE CLIENTE(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(20),
    DIRECCION VARCHAR(30),
    TELEFONO VARCHAR(11),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);
